[platformio]
default_envs = prechin_esp32s3

[env:prechin_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
board_build.flash_size = 16MB
lib_deps =
    C:/Users/26592/Documents/PlatformIO/Projects/platform_experiment/Force_Experiment/.pio/libdeps/esp32-s3-devkitc-1/Adafruit GFX Library
    C:/Users/26592/Documents/PlatformIO/Projects/platform_experiment/Force_Experiment/.pio/libdeps/esp32-s3-devkitc-1/Adafruit ST7735 and ST7789 Library
    C:/Users/26592/Documents/PlatformIO/Projects/platform_experiment/Force_Experiment/.pio/libdeps/esp32-s3-devkitc-1/XPT2046_Touchscreen
